version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongo:27017/your_database_name
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
